### ISSUE TITLE
Controlled state?

### ISSUE THREAD

**Issue by f1yingbanana** [damianricobelli/stepperize#129]
**Is your feature request related to a problem? Please describe.**
Not sure if this is already possible - but I want to control the state from the outside the component, like telling it to go to a specific step or register a callback when the stepper reaches a state.

**Describe the solution you'd like**
From outside the component, I'd like to call things similar to:
```typescript
export function MyComponent() {
  const stepper = defineStepper({ id: "a" }, { id: "b" }, { id: "c" });
  const methods = stepperuseStepper();
  const [showConfetti, setShowConfetti] = React.useState(false);
  const searchParams = useSearchParams();

  void methods.when("c", () => setShowConfetti(true));

  useEffect(() => {
    if (searchParams.get("success")) {
      methods.goTo("c");
    }
  }, [methods]);

  return (
    <>
      <stepper.Stepper>
      ...
      </stepper.Stepper>
      {showConfetti && <Confetti />}
    </>
  );
}
```

**Describe alternatives you've considered**
I think exposing the current state and having a onStateChanged callback should be great on the Stepper component. Then I can save the current state in my outer component and rerender as needed.

**Comment by damianricobelli** [comment]
Although you can check the status using the `match` method, why not do something like this?

```tsx
return (
  {methods.when("c", () => <Confetti />)}
)
```

**Comment by damianricobelli** [comment]
> I think exposing the current state and having a onStateChanged callback should be great on the Stepper component. Then I can save the current state in my outer component and rerender as needed.

Remember that we also have methods that can be executed before and after each step change.

https://stepperize.vercel.app/docs/react/api-references/hook#beforeafter-functions

**Comment by damianricobelli** [comment]
Hmm... how about using React.Portal to cover the screen with the component? It would be a very clean and simple solution.

btw, the mach method was fixed 30 minutes ago in version 5.1.6 🤝

**Comment by damianricobelli** [comment]
@f1yingbanana is this issue resolved with my last comment ? If so, let's close de issue

**Comment by f1yingbanana** [comment]
I mean it's resolved as in yes there are workarounds for my specific use case 😂 still would be nice to be able to register a onStepChanged callback from outside though 👀

**Comment by damianricobelli** [comment]
I see. Could you create a new issue explaining the uses of that callback you suggest? And close this one since it has been resolved.

**Comment by niss36** [comment]
@damianricobelli Thanks for your reply!

Yes I saw I can use those APIs to sync from the stepper to the URL -- even though it's not ideal that I have to make sure to use it everywhere I change the stepper state.

However it doesn't solve the issue of syncing from the URL to the stepper, for instance if the user clicks the browser "Back" button, which would update the `step` parameter and should make the stepper go back accordingly.
